name: ghost
services:

  ghost-server:
    image: ghost:6
    cap_add:
      - CAP_SYS_NICE
    restart: always
    depends_on:
      - ghost-db
      - ghost-tunnel
    environment:
      url: ${DOMAIN}
      database__client: mysql
      database__connection__host: ghost-db
      database__connection__user: root
      database__connection__password: ${DB_PASSWORD}
      database__connection__database: ghost
      mail__transport: SMTP 
      mail__from: ${POSTMASTER}
      mail__options__host: smtp.mailgun.org
      mail__options__port: 465
      mail__options__secure: true 
      mail__options__auth__user: ${POSTMASTER}
      mail__options__auth__pass: ${SMTP_PASSWORD}
    volumes:
      - ghost-content:/var/lib/ghost/content
    networks:
      - ghost

  ghost-db:
    image: mysql:8
    restart: always
    command: --mysql-native-password=ON
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ghost-db:/var/lib/mysql
    networks:
      - ghost

  ghost-tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: always
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - ghost

  ghost-posse:
    container_name: posse
    image: wpowiertowski/posse:latest
    restart: always
    command: poetry run posse
    volumes:
      - ./config.yml:/app/config.yml:ro
    secrets:
      - pushover_app_token
      - pushover_user_key
    networks:
      - ghost

volumes:
  ghost-db:
    external: true
  ghost-content:
    external: true

networks:
  ghost:
    external: true

# Docker secrets for Pushover credentials
# To use secrets:
# 1. Create secrets directory and secret files with your credentials:
#    mkdir -p secrets
#    printf '%s' 'YOUR_ACTUAL_APP_TOKEN_HERE' > secrets/pushover_app_token.txt
#    printf '%s' 'YOUR_ACTUAL_USER_KEY_HERE' > secrets/pushover_user_key.txt
# 2. Set pushover.enabled to true in config.yml
secrets:
  pushover_app_token:
    file: ./secrets/pushover_app_token.txt
  pushover_user_key:
    file: ./secrets/pushover_user_key.txt
